language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"

cache: pip

addons:
  apt:
    packages:
    - mongodb

install:
- 'pip install -r requirements.txt'
- 'pip install -r test-requirements.txt'

script: 'nosetests -v'
