language: python
python:
- "2.6"
- "2.7"

cache: pip

# addons:
  # apt:
    # packages:
    # - mongodb

install:
- 'pip install -r requirements.txt'
- 'pip install -r test-requirements.txt'

script: 'nosetests -v'
