language: python
python:
- "2.7"

sudo: required

cache: pip

services:
- mongodb
- docker

before_install:
- docker build -t gilzoide/labirinto:teste  --build-arg TESTE=true docker/
- docker run gilzoide/labirinto:teste /etc/my_init.d/init-labirinto.sh

install:
- 'pip install -r requirements.txt'
- 'pip install -r test-requirements.txt'

script: 'nosetests -v'
