language: python
python:
- "2.7"

sudo: required

cache: pip

services:
- mongodb
- docker

before_install:
- docker build -t gilzoide/labirinto docker/
- docker run gilzoide/labirinto /bin/bash -c "pip install -r test-requirements.txt; mongod --dbpath /db &; nosetests"

install:
- 'pip install -r requirements.txt'
- 'pip install -r test-requirements.txt'

script: 'nosetests -v'
