language: python
python:
- "2.7"

sudo: required

cache: pip

services:
- mongodb
- docker

install:
- 'pip install -r requirements.txt'
- 'pip install -r test-requirements.txt'
- 'docker build -t gilzoide/labirinto:teste  --build-arg ACTION=teste docker/'

script: 
- 'docker run gilzoide/labirinto:teste /sbin/my_init -- nosetests'
- 'nosetests -v'
