# -*- coding: utf-8 -*-

import os

MONGODB_DB = 'sessoes'
MONGODB_HOST = os.environ['MONGO_PORT_27017_TCP_ADDR']
MONGODB_PORT = os.environ['MONGO_PORT_27017_TCP_PORT']

SECRET_KEY = '8f01ee08-f0e8-429e-9448-73042a51d9d2'
SECURITY_PASSWORD_HASH = 'pbkdf2_sha512'
SECURITY_PASSWORD_SALT = SECRET_KEY
SECURITY_REGISTERABLE = True

# admin mais facil, tirar no produção
SECURITY_SEND_REGISTER_EMAIL = False
SECURITY_LOGIN_WITHOUT_CONFIRMATION = True
SECURITY_CHANGEABLE = True
